namespace CA_Hospital_Management.Models.Enums
{
    public enum CountiesEnum
    {
        Carlow,
        Cavan,
        Clare, 
        Cork, 
        Donegal, 
        Dublin, 
        Galway, 
        Kerry,   
        Kildare, 
        Kilkenny, 
        Laois, 
        Leitrim, 
        Limerick, 
        Longford, 
        Louth,
        Mayo, 
        Meath, 
        Monaghan, 
        Offaly, 
        Roscommon, 
        Sligo, 
        Tipperary,
        Waterford, 
        Westmeath, 
        Wexford, 
        Wicklow 
    }
}
